[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/game/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
